import { BusinessCard } from '../types';

export const sampleCards: BusinessCard[] = [
  {
    id: '1',
    name: '山田 太郎',
    company: '株式会社テクノロジー',
    title: '営業部長',
    email: 'yamada@example.com',
    phone: '03-1234-5678',
    address: '東京都渋谷区渋谷1-1-1 テクノビル10F',
    website: 'https://example.com',
    notes: '2024年の展示会で出会いました。AI事業に興味あり。',
    imageUri: '',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
    tags: ['営業', 'AI', '東京'],
    isFavorite: true,
  },
  {
    id: '2',
    name: '佐藤 花子',
    company: 'デザインスタジオ クリエイティブ',
    title: 'クリエイティブディレクター',
    email: 'sato@creative.jp',
    phone: '090-9876-5432',
    address: '東京都港区南青山3-2-1',
    website: 'https://creative.jp',
    notes: 'UIデザインのエキスパート。次回プロジェクトで協力予定。',
    imageUri: '',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
    tags: ['デザイン', 'UI/UX'],
    isFavorite: true,
  },
  {
    id: '3',
    name: '鈴木 一郎',
    company: 'イノベーション株式会社',
    title: 'CTO',
    email: 'suzuki@innovation.co.jp',
    phone: '03-9999-8888',
    address: '東京都千代田区丸の内1-1-1',
    website: 'https://innovation.co.jp',
    notes: 'クラウドインフラに詳しい。技術相談可能。',
    imageUri: '',
    createdAt: new Date('2024-03-10'),
    updatedAt: new Date('2024-03-10'),
    tags: ['技術', 'クラウド'],
    isFavorite: false,
  },
  {
    id: '4',
    name: '田中 美咲',
    company: 'マーケティングエージェンシー',
    title: 'マーケティングマネージャー',
    email: 'tanaka@marketing.com',
    phone: '045-123-4567',
    address: '神奈川県横浜市西区みなとみらい2-2-2',
    website: 'https://marketing.com',
    notes: 'SNSマーケティングの専門家',
    imageUri: '',
    createdAt: new Date('2024-04-05'),
    updatedAt: new Date('2024-04-05'),
    tags: ['マーケティング', 'SNS'],
    isFavorite: false,
  },
  {
    id: '5',
    name: '高橋 健太',
    company: 'スタートアップベンチャー',
    title: 'CEO',
    email: 'takahashi@startup.io',
    phone: '080-1111-2222',
    address: '東京都渋谷区恵比寿1-1-1',
    website: 'https://startup.io',
    notes: '資金調達を検討中。投資機会あり。',
    imageUri: '',
    createdAt: new Date('2024-05-15'),
    updatedAt: new Date('2024-05-15'),
    tags: ['スタートアップ', '投資'],
    isFavorite: false,
  },
];

export const loadSampleData = async (saveCard: (card: BusinessCard) => Promise<void>) => {
  for (const card of sampleCards) {
    await saveCard(card);
  }
};